#!/bin/bash
cd /home/kevin/minecraft/Minecraft-Overviewer
wget -N http://s3.amazonaws.com/MinecraftDownload/minecraft.jar -P ~/.minecraft/bin/
rsync -a ../world .
python overviewer.py --config config.py
python overviewer.py --config config.py --genpoi
