#!/bin/bash
cd "$( dirname "$0" )"
export VERSION=1.8
wget -N https://s3.amazonaws.com/Minecraft.Download/versions/$VERSION/${VERSION}.jar -P ~/.minecraft/versions/$VERSION/
rsync -a --delete ../world .
python overviewer.py --config config.py
python overviewer.py --config config.py --genpoi
