#!/bin/bash
cd "$( dirname "$0" )"
wget -N http://s3.amazonaws.com/MinecraftDownload/minecraft.jar -P ~/.minecraft/bin/
python overviewer.py --config config-exmaple.py
python overviewer.py --config config-exmaple.py --genpoi
