#!/bin/bash
cd "$( dirname "$0" )"
wget -N http://s3.amazonaws.com/MinecraftDownload/minecraft.jar -P ~/.minecraft/bin/
rsync -a --delete ../world .
python overviewer.py --config config.py
python overviewer.py --config config.py --genpoi

keychain id_rsa
. ~/.keychain/`uname -n`-sh
rsync -acvz --files-from=rsync-include -e ssh /var/www/minecraft/map/ nfsipm:/home/public/
