#!/bin/bash
cd /home/kevin/minecraft/Minecraft-Overviewer
wget -N http://s3.amazonaws.com/MinecraftDownload/minecraft.jar -P ~/.minecraft/bin/
python overviewer.py --config config-exmaple.py
python overviewer.py --config config-exmaple.py --genpoi
